package com.ascend.workflow.domain.service;

import com.ascend.workflow.domain.model.InstanceStep;
import com.ascend.workflow.infrastructure.repository.InstanceStepRepository;
import com.ascend.workflow.infrastructure.repository.WorkflowInstanceRepository;
import com.ascend.workflow.infrastructure.repository.WorkflowStepRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import reactor.core.publisher.Mono;

import java.time.OffsetDateTime;
import java.util.Map;
import java.util.UUID;

@Slf4j
@Component
@RequiredArgsConstructor
public class EscalationScheduler {

    // system user ID used for audit entries generated by the scheduler
    private static final UUID SYSTEM_USER_ID = UUID.fromString("00000000-0000-0000-0000-000000000001");

    private final InstanceStepRepository instanceStepRepository;
    private final WorkflowStepRepository workflowStepRepository;
    private final WorkflowInstanceRepository instanceRepository;
    private final AuditService auditService;

    @Scheduled(fixedDelayString = "${app.escalation.interval-ms:900000}") // default 15 min
    public void processEscalations() {
        log.debug("Running escalation check");
        instanceStepRepository.findEscalationCandidates()
                .flatMap(this::escalate)
                .subscribe(
                        step -> log.info("Escalated step: {}", step.getId()),
                        err  -> log.error("Escalation error", err)
                );
    }

    private Mono<InstanceStep> escalate(InstanceStep step) {
        return workflowStepRepository.findById(step.getStepId())
                .flatMap(workflowStep -> {
                    UUID escalateTo = workflowStep.getEscalationUserId();

                    // Mark original step as ESCALATED — escalated_at guards against re-processing
                    step.setStatus("ESCALATED");
                    step.setEscalatedAt(OffsetDateTime.now());
                    step.setEscalatedToUserId(escalateTo);
                    step.setCompletedAt(OffsetDateTime.now());

                    // Create a new PENDING step assigned to the escalation user
                    InstanceStep escalatedStep = InstanceStep.builder()
                            .instanceId(step.getInstanceId())
                            .stepId(step.getStepId())
                            .stepOrder(step.getStepOrder())
                            .parallelGroup(step.getParallelGroup())
                            .status("PENDING")
                            .startedAt(OffsetDateTime.now())
                            .build();

                    return instanceStepRepository.save(step)
                            .then(instanceStepRepository.save(escalatedStep))
                            .then(instanceRepository.findById(step.getInstanceId()))
                            .flatMap(instance -> auditService.log(
                                    instance.getId(), SYSTEM_USER_ID, "STEP_ESCALATED",
                                    Map.of("fromStep", step.getId().toString(),
                                           "escalatedTo", escalateTo.toString(),
                                           "reason", "timeout")))
                            .thenReturn(step);
                });
    }
}
